### PR TITLE
add azure functions support

### PR DESCRIPTION
**Pull request by trevorwang**
add Azure Functions Support
add integration sample code

### CODE REVIEW

**Comment by trevorwang** [comment]
#102

**Comment by jankoenig** [comment]
Thanks a lot, that was fast!

We're traveling the rest of the week, but will take a look and ideally make this part of our v1.1 release next week. Thanks for contributing 🎉

**Comment by aswetlow** [comment]
Hey @trevorwang! Thank you for your pull request. Unfortunately I can't get your example to work. Which DB do you use?

**Comment by trevorwang** [comment]
Actually I didn't do any special config for DB

**Pull request merged**
