### PR TITLE
Feature/azure functions docs

### PR DESCRIPTION
**Pull request by IGx89**
## Proposed changes
Documentation on Azure Functions support

### CODE REVIEW

**Comment by IGx89** [comment]
CC @trevorwang

**Comment by jankoenig** [comment]
This is amazing, thanks a lot!

**Comment by IGx89** [comment]
Glad to help out, @jankoenig! BTW, I noticed that the new page isn't showing up in the navigation tree (left side of the page). Did I miss adding it to a file or is that a configuration on the site itself?

**Comment by jankoenig** [comment]
Ah yes! This isn't fully automated yet, going to add it manually. Thanks

**Pull request merged**
