### PR TITLE
Feature/playback controller

### PR DESCRIPTION
**Pull request by vitaliidanchul**
Implementing playback controller

### CODE REVIEW

**Comment by jankoenig** [comment]
Wow, this has never happened before: Basically the same pull request by two different people on the same day! (see #227).

Thanks a lot for this. We will take a closer look and see how we can merge it with the other contribution. 👍 Cool stuff

**Comment by vitaliidanchul** [comment]
Oh, didn't see that) #227 will not send response, if we use `this.alexaSkill().audioPlayer().setOffsetInMilliseconds(this.user().data.offset).play(song);`

**Comment by aswetlow** [comment]
Thanks @vitaliidanchul 
Yeah, you are right. This part was missing: ` || this.jovo.isPlaybackControllerRequest()`

`PlaybackController.PauseCommandIssued` never gets fired (tested on my Android phone). Does that work for you?

**Comment by vitaliidanchul** [comment]
@aswetlow , no it doesn't work for me, too. some devices handle pause locally:
image

**Pull request merged**
